# See FortifyVulnerabilityExporter documentation for FoD connection settings and release selection

export:
  from: fod
  to: json.custom   # You can use any name, as long as it starts with 'json' and there is a corresponding configuration entry

fod:
  vulnerability:
    filterParam: severityString:Critical # Example to have FoD return only Critical issues
    embed:                               # Load extra data, depending on what data you want to include in output
      - subEntity: details                       

export.dir: ${export.default.dir}      # Use default export directory (unless overridden)
json.custom:
  output:
    stdout: true                       # Useful for debugging, disable for optimal performance
    pretty: true                       # Useful for debugging, disable for optimal performance
    file:   ${export.dir}/${release.applicationName}-${release.releaseName}.json # Output file
  format:
    fields:
      hello: there
      vulnerabilitiesArray: $[vulnerabilityMappers.vulnerability.get()]     # Reference to vulnerabilityMapper defined below
      vulnerabilitiesById:  $[vulnerabilityMappers.vulnerabilityById.get()] # Reference to vulnerabilityMapper defined below
      explanationsById:     $[vulnerabilityMappers.explanationById.get()]   # Reference to vulnerabilityMapper defined below
    vulnerabilityMappers:
      vulnerability:
        fields:
          id: $[vuln.instanceId]
          description: $[#htmlToText(vuln.details?.explanation)]
          release: $[release.applicationAndReleaseName]
      vulnerabilityById:
        propertyName: $[vuln.instanceId]
        fields:
          id: $[vuln.instanceId]
          description: $[#htmlToText(vuln.details?.explanation)]
          release: $[release.applicationAndReleaseName]
      explanationById:
        propertyName: $[vuln.instanceId]
        value: $[#htmlToText(vuln.details?.explanation)]
      
    