# See FortifyVulnerabilityExporter documentation for FoD connection settings and release selection

export:
  from: fod
  to: json.sonarqube.sast

fod:
  vulnerability:
    filterParam: scantype:Static             # Have FoD return only static issues 

json.sonarqube.sast.filePathPrefix:          # By default don't add any prefix to the path (used in json-sonarqube-fod-sast.yml)
export.dir: ${export.default.dir}            # Use default export directory (unless overridden)
json.sonarqube.sast.output:
  stdout: false                              # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                               # Useful for debugging, disable for optimal performance
  file:   ${export.dir}/sq-fortify-sast.json # Output file