# See FortifyVulnerabilityExporter documentation for SSC connection settings and application version selection

export:
  from: ssc
  to: json.bitbucket.sast.report, json.bitbucket.sast.annotations

ssc:
  version:
    embed:
      - subEntity: currentStaticScan
        onError: LOG_INFO
      - propertyName: issueCountsSCA
        subEntity: issueGroups
        params:
          filter: ISSUE[11111111-1111-1111-1111-111111111151]:SCA
          groupingtype: 11111111-1111-1111-1111-111111111150
      - propertyName: issueCounts
        subEntity: issueGroups
        params:
          groupingtype: 11111111-1111-1111-1111-111111111150
  vuln:
    filterParam: ISSUE[11111111-1111-1111-1111-111111111151]:SCA   # Have SSC return only SCA issues
    embed:                                                         # Also load details as required for GitHub output
      - subEntity: details                                         

export.dir: ${BITBUCKET_WORKSPACE:${export.default.dir}}                # Unless overridden, use BITBUCKET_WORKSPACE if defined, otherwise default export dir
bitbucket.report.output: ${export.dir}/bb-fortify-report.json           # Define default report output file location and name
bitbucket.annotations.output: ${export.dir}/bb-fortify-annotations.json # Define default annotations output file location and name

json.bitbucket.sast.report.output:
  stdout: false                                           # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                                            # Useful for debugging, disable for optimal performance
  file:   ${bitbucket.report.output}                      # Output file
json.bitbucket.sast.annotations.output:
  stdout: false                                           # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                                            # Useful for debugging, disable for optimal performance
  file:   ${bitbucket.annotations.output}                 # Output file