# See FortifyVulnerabilityExporter documentation for SSC connection settings and application version selection

export:
  from: ssc
  to: json.gitlab.debricked

ssc:
  version:
    embed:
      - subEntity: currentDebrickedScan
        onError: LOG_INFO
  vulnerability:
    filterParam: ISSUE[11111111-1111-1111-1111-111111111151]:DEBRICKED   # Have SSC return only Debricked issues
    embed:                                                              # Also load details as required for GitLab output
      - subEntity: details                                                 

export.dir: ${CI_PROJECT_DIR:${export.default.dir}}    # Unless overridden, use CI_PROJECT_DIR if defined, otherwise default export dir
json.gitlab.debricked.output:
  stdout: false                                        # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                                         # Useful for debugging, disable for optimal performance
  file:   ${export.dir}/gl-fortify-debricked-depscan.json        # Output file
  