# See FortifyVulnerabilityExporter documentation for SSC connection settings and application version selection

export:
  from: ssc
  to: json.sonarqube.sast

ssc:
  vulnerability:
    filterParam: ISSUE[11111111-1111-1111-1111-111111111151]:SCA   # Have SSC return only SCA issues

json.sonarqube.sast.filePathPrefix:          # By default don't add any prefix to the path  (used in json-sonarqube-ssc-sast.yml)
export.dir: ${export.default.dir}            # Use default export directory (unless overridden)
json.sonarqube.sast.output:
  stdout: false                              # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                               # Useful for debugging, disable for optimal performance
  file:   ${export.dir}/sq-fortify-sast.json # Output file
  